CREATE DATABASE 'localhost:db_controlcomb'
USER 'SYSDBA' PASSWORD '**********'
PAGE_SIZE 4096
DEFAULT CHARACTER SET NONE;

/* Roles */
CREATE ROLE RDB$ADMIN;

/* Generators */
CREATE SEQUENCE GEN_TB_VENDATC1_ID;

ALTER SEQUENCE GEN_TB_VENDATC1_ID RESTART WITH 14;
CREATE SEQUENCE SEQ_VENDATC1;

ALTER SEQUENCE SEQ_VENDATC1 RESTART WITH 1;
CREATE SEQUENCE SEQ_VENDATC2;

ALTER SEQUENCE SEQ_VENDATC2 RESTART WITH 4;

/* Procedures */
SET TERM ^ ;
RECREATE PROCEDURE SP_GEN_TB_VENDATC1_ID
RETURNS (
 ID INTEGER)
AS 
BEGIN
  /* Procedure text */
END^

RECREATE PROCEDURE SP_GEN_TB_VENDATC2_ID
RETURNS (
 ID INTEGER)
AS 
BEGIN
  /* Procedure text */
END^
SET TERM ; ^

/* Tables */
CREATE TABLE TB_PERCIMPOSTO (
  PERCENTUAL  NUMERIC(9,2)
) ;

CREATE TABLE TB_PRECOGASOL (
  PRECO  NUMERIC(9,2)
) ;

CREATE TABLE TB_PRECOOLEO (
  PRECO  NUMERIC(9,2)
) ;

CREATE TABLE TB_VENDATC1 (
  CONTADOR            INTEGER NOT NULL,
  PRECO               NUMERIC(9,2) NOT NULL,
  "DATA"              DATE NOT NULL,
  QUANTIDADE          NUMERIC(9,2) NOT NULL,
  PRECO_VENDA         NUMERIC(9,2) NOT NULL,
  PERCENTUAL_IMPOSTO  NUMERIC(9,2) NOT NULL,
  BOMBA_GASOL         INTEGER NOT NULL,
  VALOR_IMPOSTO       NUMERIC(9,2) NOT NULL
) ;

CREATE TABLE TB_VENDATC2 (
  CONTADOR            INTEGER NOT NULL,
  PRECO               NUMERIC(9,2) NOT NULL,
  "DATA"              DATE NOT NULL,
  QUANTIDADE          NUMERIC(9,2) NOT NULL,
  PRECO_VENDA         NUMERIC(9,2) NOT NULL,
  PERCENTUAL_IMPOSTO  NUMERIC(9,2) NOT NULL,
  BOMBA_OLEO          INTEGER NOT NULL,
  VALOR_IMPOSTO       NUMERIC(9,2) NOT NULL
) ;
COMMIT;

/* Indexes */
CREATE UNIQUE INDEX TB_VENDATC1_INDEX01
  ON TB_VENDATC1
  (CONTADOR);
CREATE UNIQUE INDEX TB_VENDATC2_INDEX01
  ON TB_VENDATC2
  (CONTADOR);

/* Constraints */
ALTER TABLE TB_VENDATC1
  ADD PRIMARY KEY (CONTADOR);

ALTER TABLE TB_VENDATC2
  ADD PRIMARY KEY (CONTADOR);

/* Triggers */
SET TERM ^ ;
CREATE TRIGGER TB_VENDATC1_BI FOR TB_VENDATC1
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.CONTADOR IS NULL) THEN
    NEW.CONTADOR = GEN_ID(GEN_TB_VENDATC1_ID,1);
END^

CREATE TRIGGER TB_VENDATC2_BI FOR TB_VENDATC2
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.CONTADOR IS NULL) THEN
    NEW.CONTADOR = GEN_ID(SEQ_VENDATC2,1);
END^
SET TERM ; ^

/* Procedures */
SET TERM ^ ;
ALTER PROCEDURE SP_GEN_TB_VENDATC1_ID
RETURNS (
 ID INTEGER)
AS 
BEGIN
  ID = GEN_ID(GEN_TB_VENDATC1_ID, 1);
  SUSPEND;
END^

ALTER PROCEDURE SP_GEN_TB_VENDATC2_ID
RETURNS (
 ID INTEGER)
AS 
BEGIN
  ID = GEN_ID(SEQ_VENDATC2, 1);
  SUSPEND;
END^
SET TERM ; ^

/* Data for table "TB_PERCIMPOSTO" */
INSERT INTO TB_PERCIMPOSTO (PERCENTUAL) VALUES (5);
COMMIT;

/* Data for table "TB_PRECOGASOL" */
INSERT INTO TB_PRECOGASOL (PRECO) VALUES (3.29);
COMMIT;

/* Data for table "TB_PRECOOLEO" */
INSERT INTO TB_PRECOOLEO (PRECO) VALUES (2.77);
COMMIT;

/* Data for table "TB_VENDATC1" */
INSERT INTO TB_VENDATC1 (CONTADOR, PRECO, "DATA", QUANTIDADE, PRECO_VENDA, PERCENTUAL_IMPOSTO, BOMBA_GASOL, VALOR_IMPOSTO) VALUES (14, 3.29, '2016-06-07', 2.74, 9, 5, 2, 0.45);
INSERT INTO TB_VENDATC1 (CONTADOR, PRECO, "DATA", QUANTIDADE, PRECO_VENDA, PERCENTUAL_IMPOSTO, BOMBA_GASOL, VALOR_IMPOSTO) VALUES (12, 3.29, '2016-06-07', 5, 16.45, 13, 1, 2.14);
INSERT INTO TB_VENDATC1 (CONTADOR, PRECO, "DATA", QUANTIDADE, PRECO_VENDA, PERCENTUAL_IMPOSTO, BOMBA_GASOL, VALOR_IMPOSTO) VALUES (13, 3.29, '2016-06-07', 5.17, 17, 13, 2, 2.21);
COMMIT;

/* Data for table "TB_VENDATC2" */
INSERT INTO TB_VENDATC2 (CONTADOR, PRECO, "DATA", QUANTIDADE, PRECO_VENDA, PERCENTUAL_IMPOSTO, BOMBA_OLEO, VALOR_IMPOSTO) VALUES (1, 2.77, '2016-06-07', 10, 27.7, 5, 2, 1.39);
INSERT INTO TB_VENDATC2 (CONTADOR, PRECO, "DATA", QUANTIDADE, PRECO_VENDA, PERCENTUAL_IMPOSTO, BOMBA_OLEO, VALOR_IMPOSTO) VALUES (2, 2.77, '2016-06-07', 7, 19.39, 5, 1, 0.97);
INSERT INTO TB_VENDATC2 (CONTADOR, PRECO, "DATA", QUANTIDADE, PRECO_VENDA, PERCENTUAL_IMPOSTO, BOMBA_OLEO, VALOR_IMPOSTO) VALUES (3, 2.77, '2016-06-07', 8, 22.16, 5, 1, 1.11);
INSERT INTO TB_VENDATC2 (CONTADOR, PRECO, "DATA", QUANTIDADE, PRECO_VENDA, PERCENTUAL_IMPOSTO, BOMBA_OLEO, VALOR_IMPOSTO) VALUES (4, 2.77, '2016-06-07', 5, 13.85, 5, 2, 0.69);
COMMIT;

